- name: 
  hosts: localhost
  gather_facts: no
  tasks:
  - name: BGP Elements
    register: result
    bgp_element:
      smc_logging:
        level: 10
        path: ansible-smc.log
      elements:
        - ip_access_list: 
            name: myservice2
            comment: my ip acl
            entries: 
             - subnet: 1.1.4.0/24
               action: permit
             - subnet: 2.2.2.0/24
               action: deny
        - ip_prefix_list:
            name: aprefix
            comment: prefix lists without min and max prefix
            entries:
              - subnet: 10.0.0.0/8
                action: deny
              - subnet: 192.16.2.0/24
                action: permit
        - ipv6_access_list:
            name: myipv6acl
            comment: an ipv6 acl
            entries:
              - subnet: '2001:db8:1::1/128'
                action: permit
        - ipv6_prefix_list:
            name: ipv6prefix
            entries:
              - subnet: 'ab00::/64'
                min_prefix_length: 65
                max_prefix_length: 128
                action: deny
        - as_path_access_list:
            name: mytestaccesslist
            comment: an as path
            entries:
              - expression: '123-456'
                action: permit
              - expression: '1234-567'
                action: deny
        - community_access_list:
            name: cmtyacl
            type: standard
            comment: my community
            entries:
              - community: '123'
                action: permit
              - community: '456'
                action: deny
        - extended_community_access_list:
            name: extcommacl
            type: standard
            comment: Some acl
            entries:
              - community: '123'
                action: permit
                type: rt
              - community: '456'
                action: deny
                type: soo
        - bgp_peering:
            name: extpeer
            comment: my peering
        - external_bgp_peer:
            name: mypeer666
            neighbor_as: myas123
            neighbor_ip: 12.12.12.12
            neighbor_port: 179
            comment: mypeer
        - autonomous_system:
            name: myas123
            as_number: '123.123'
            comment: foo comment
      state: absent
      #overwrite_existing: true
        

          